"""Add Colors in Status and Severity

Revision ID: 0b8fb24040a6
Revises: 18d107db9c93
Create Date: 2024-04-04 14:16:35.567872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8fb24040a6'
down_revision = '18d107db9c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('severity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=15), nullable=False))

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_column('color')

    with op.batch_alter_table('severity', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
