"""Add company_name Column in User

Revision ID: 7a9c69a65843
Revises: 596e848b69bc
Create Date: 2024-03-17 15:30:12.973853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9c69a65843'
down_revision = '596e848b69bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=40), nullable=False))
        batch_op.create_unique_constraint(None, ['company_name'])
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
