"""create Project Table

Revision ID: 904728a3684e
Revises: 4c4035f0cd40
Create Date: 2024-03-20 18:25:18.966092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904728a3684e'
down_revision = '4c4035f0cd40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
