"""Update User company_id Column

Revision ID: e12f2a32e868
Revises: 45351b289697
Create Date: 2024-03-19 13:59:07.363902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e12f2a32e868'
down_revision = '45351b289697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
