"""Add description column in Severity Table

Revision ID: e4877e8ead6f
Revises: 079ac37a448e
Create Date: 2024-04-01 12:15:22.798248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4877e8ead6f'
down_revision = '079ac37a448e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('severity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('severity', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
